baseURL = 'https://kroket.nexaa.io/'
languageCode = 'en-us'
title = 'Kroket Friday'
theme = 'fluency'
[menus]
  [[menus.footer]]
    name= 'Github'
    url= 'https://github.com/nexaa-cloud/kroket'
    weight = 30
  [[menus.footer]]
    name= 'Hosted by Nexaa'
    pre = '<i class="fa fa-heart"></i>'
    url= 'https://nexaa.io?utm_source=kroket&utm_medium=footer&utm_campaign=2025'
    weight = 30

copyright = "© 2021 <a href='https://github.com/wayjam/hugo-theme-fluency'>Hugo Theme Fluency</a>."

[params]
  # Add your custom JavaScript here
  customScript = '''
  <script
    src="https://analytics.nexaa.io/api/script.js"
    data-site-id="4"
    defer
  ></script>
  '''
