baseURL = 'https://kroket.nexaa.io/'
languageCode = 'en-us'
title = 'Kroket Friday'
theme = 'hugo-theme-console'
[menus]
  [[menus.footer]]
    name= 'Github'
    url= 'https://github.com/nexaa-cloud/kroket'
    weight = 30
  [[menus.footer]]
    name= 'Hosted by Nexaa'
    pre = '<i class="fa fa-heart"></i>'
    url= 'https://nexaa.io?utm_source=kroket&utm_medium=footer&utm_campaign=2025'
    weight = 30

[params]
  customScript = '''
  <script
    src="https://analytics.nexaa.io/api/script.js"
    data-site-id="4"
    defer
  ></script>
  '''

[imaging]
  resampleFilter = "box"
  quality = 75
  anchor = "smart"
