name: Build and Publish

on:
  push:
    branches:
      - main  # Or your default branch
  workflow_dispatch:  # Allows manual triggering

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive  # In case your Hugo theme is a submodule

      - name: Set up Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.148.2'  # Match the version in your Makefile
          extended: true  # Use the extended version if needed

      - name: Build site
        run: hugo --minify

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate tag with date and time
        id: tag
        run: echo "TAG=$(date +'%Y-%m-%d %H:%M' | sed 's/ /-/g' | sed 's/:/./g')" >> $GITHUB_OUTPUT

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/kroket:latest
            ghcr.io/${{ github.repository_owner }}/kroket:${{ steps.tag.outputs.TAG }}
